name: rikulo_orm
version: 0.5.0
author: Henri Chen <henrichen@rikulo.org>
description: Rikulo ORM is an Object-relational mapping package for Dart.
homepage: http://rikulo.org
dependencies:
  rikulo_commons: any
dev_dependencies:
  unittest: any
